ficha6.exe : main.o Stack.o Queue.o 
  gcc -oo ficha6.exe main.o Stack.o Queue.o

main.o : main.c Stack.h Queue.h
  gcc -c main.c

Stack.o : Stack.c Stack.h
  gcc -c Stack.c

Queue. : Queue.c Queue.c
  gcc -c Queue.c
